spring:
  datasource:
    url: jdbc:mysql://mysql/ufscar?createDatabaseIfNotExist=true
    username: root
    password: root
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus